spring:
  dynamic:
    thread-pool:
      # 开关
      enable: false
      # 服务端地址
      server-addr: http://localhost:6691
      # 用户名
      username: admin
      # 密码
      password: 123456
      # 租户 id, 对应 tenant 表
      namespace: demo-boot-redis
      # 项目 id, 对应 item 表
      item-id: ${spring.application.name}
