server:
  port: 9239
spring:
  application:
    name: demo-boot-statemachine
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-gs5q573fvex10s40x.mysql.singapore.rds.aliyuncs.com:3306/payment_system?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
    username: agilewingadmin
    password: fZ1etRWXUpTQk8VEmI

logging:
  level:
    root: info
    com.sofwin: debug

# MyBatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.mudxx.demo.boot.statemachine.dao.mapper
  configuration:
    #打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
