server:
  port: 9236
spring:
  application:
    name: demo-boot-jpa
  profiles:
    include: jdbc,redis

security:
  max-seconds: 3000
#  redis-key: TEST:TTT
#  header-timestamp: X-1
#  header-sign: X-2
#  header-nonce: X-3